default: &default
  adapter: <%= ENV.fetch('DB_ADAPTER') { 'postgresql' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: <%= ENV.fetch('PG_TIMEOUT') { 5000 } %>
  host: <%= ENV.fetch('PG_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('PG_USERNAME') { 'pguser' } %>
  password: <%= ENV.fetch('PG_PASSWORD') { 'password' } %>

development:
  <<: *default
  database: siege-engine/development
  pool: 30

test:
  <<: *default
  database: siege-engine/test

production:
  <<: *default
  database: siege-engine/production
