default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: jc
  password: 

development:
  <<: *default
  database: siege-engine/development
  pool: 30

test:
  <<: *default
  database: siege-engine/test

production:
  <<: *default
  database: siege-engine/production
